apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-f
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-f
  template:
    metadata:
      labels:
        app: service-f
    spec:
      containers:
      - name: service-f
        image: openjdk:17-jdk
        command: ["java", "-jar", "/app/service-f.jar"]
        ports:
        - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: service-f
spec:
  selector:
    app: service-f
  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8086